import { Manrope } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"

export const biggerFont = localFont({
  src: "../public/fonts/BiggerDisplay.woff",
  display: "swap",
  family: "Bigger Display, sans-serif",
})

const manrope = Manrope({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>{children}</body>
    </html>
  )
}
